from django.urls import path

from .views import (
    academic_year_create,
    academic_year_list,
    academic_year_set_active,
    announcement_create,
    announcement_delete,
    announcement_list,
    announcement_update,
    assignment_create,
    assignment_delete,
    assignment_list,
    assignment_submission_detail,
    assignment_submission_list,
    assignment_submission_open,
    assignment_submission_review,
    assignment_update,
    attendance_create,
    attendance_delete,
    attendance_list,
    attendance_update,
    dashboard_home,
    grade_create,
    grade_delete,
    grade_list,
    grade_update,
    student_create,
    student_list,
    student_update,
    student_delete,
    student_delete_confirm,
    regenerate_parent_code,
    teacher_list,
    teacher_create,
    teacher_update,
    parent_delete,
    parent_delete_confirm,
    parent_list,
    parent_update,
    invoice_create,
    invoice_delete,
    invoice_list,
    invoice_update,
    notification_broadcast,
    notification_delete,
    notification_detail,
    notification_list,
    notification_preference_list,
    notification_preference_update,
    notification_reminder_center,
    notification_template_list,
    notification_template_update,
    notification_toggle_read,
    payment_list,
    promotion_calculate,
    promotion_publish,
    promotion_result_detail,
    promotion_results,
    receipt_detail,
    receipt_list,
    push_deactivate_invalid_devices,
    push_diagnostics,
    push_delivery_detail,
    push_delivery_list,
    push_delivery_retry,
    push_device_send_test,
    push_device_list,
    push_device_toggle_active,
    push_flutter_contract,
    schedule_create,
    schedule_delete,
    schedule_list,
    schedule_update,
    classroom_create,
    classroom_delete,
    classroom_list,
    classroom_update,
    section_create,
    section_delete,
    section_list,
    section_update,
    subject_create,
    subject_delete,
    subject_list,
    subject_update,
    teaching_assignment_create,
    teaching_assignment_delete,
    teaching_assignment_list,
    teaching_assignment_update,
    uploaded_file_create,
    uploaded_file_delete,
    uploaded_file_detail,
    uploaded_file_list,
    uploaded_file_open,
)

app_name = "dashboard"

urlpatterns = [
    path("", dashboard_home, name="home"),
    path("students/", student_list, name="student-list"),
    path("students/create/", student_create, name="student-create"),
    path("students/<int:student_id>/edit/", student_update, name="student-update"),
    path(
        "students/<int:student_id>/delete/",
        student_delete_confirm,
        name="student-delete-confirm",
    ),
    path(
        "students/<int:student_id>/delete/confirm/",
        student_delete,
        name="student-delete",
    ),
    path(
        "students/<int:student_id>/regenerate-code/",
        regenerate_parent_code,
        name="student-regenerate-code",
    ),
    path("teachers/", teacher_list, name="teacher-list"),
    path("teachers/create/", teacher_create, name="teacher-create"),
    path("teachers/<int:teacher_id>/edit/", teacher_update, name="teacher-update"),
    path("parents/", parent_list, name="parent-list"),
    path("parents/<int:parent_id>/edit/", parent_update, name="parent-update"),
    path(
        "parents/<int:parent_id>/delete/",
        parent_delete_confirm,
        name="parent-delete-confirm",
    ),
    path(
        "parents/<int:parent_id>/delete/confirm/", parent_delete, name="parent-delete"
    ),
    path("invoices/", invoice_list, name="invoice-list"),
    path("invoices/create/", invoice_create, name="invoice-create"),
    path("invoices/<int:invoice_id>/edit/", invoice_update, name="invoice-update"),
    path("invoices/<int:invoice_id>/delete/", invoice_delete, name="invoice-delete"),
    path("payments/", payment_list, name="payment-list"),
    path("receipts/", receipt_list, name="receipt-list"),
    path("receipts/<int:receipt_id>/", receipt_detail, name="receipt-detail"),
    path("schedules/", schedule_list, name="schedule-list"),
    path("schedules/create/", schedule_create, name="schedule-create"),
    path("schedules/<int:schedule_id>/edit/", schedule_update, name="schedule-update"),
    path("schedules/<int:schedule_id>/delete/", schedule_delete, name="schedule-delete"),
    path("attendance/", attendance_list, name="attendance-list"),
    path("attendance/create/", attendance_create, name="attendance-create"),
    path(
        "attendance/<int:attendance_id>/edit/",
        attendance_update,
        name="attendance-update",
    ),
    path(
        "attendance/<int:attendance_id>/delete/",
        attendance_delete,
        name="attendance-delete",
    ),
    path("grades/", grade_list, name="grade-list"),
    path("grades/create/", grade_create, name="grade-create"),
    path("grades/<int:grade_id>/edit/", grade_update, name="grade-update"),
    path("grades/<int:grade_id>/delete/", grade_delete, name="grade-delete"),
    path("assignments/", assignment_list, name="assignment-list"),
    path("assignments/create/", assignment_create, name="assignment-create"),
    path(
        "assignments/<int:assignment_id>/edit/",
        assignment_update,
        name="assignment-update",
    ),
    path(
        "assignments/<int:assignment_id>/delete/",
        assignment_delete,
        name="assignment-delete",
    ),
    path(
        "assignment-submissions/",
        assignment_submission_list,
        name="assignment-submission-list",
    ),
    path(
        "assignment-submissions/<int:submission_id>/",
        assignment_submission_detail,
        name="assignment-submission-detail",
    ),
    path(
        "assignment-submissions/<int:submission_id>/open/",
        assignment_submission_open,
        name="assignment-submission-open",
    ),
    path(
        "assignment-submissions/<int:submission_id>/review/",
        assignment_submission_review,
        name="assignment-submission-review",
    ),
    path("uploaded-files/", uploaded_file_list, name="uploaded-file-list"),
    path("uploaded-files/create/", uploaded_file_create, name="uploaded-file-create"),
    path(
        "uploaded-files/<int:uploaded_file_id>/",
        uploaded_file_detail,
        name="uploaded-file-detail",
    ),
    path(
        "uploaded-files/<int:uploaded_file_id>/open/",
        uploaded_file_open,
        name="uploaded-file-open",
    ),
    path(
        "uploaded-files/<int:uploaded_file_id>/delete/",
        uploaded_file_delete,
        name="uploaded-file-delete",
    ),
    path("announcements/", announcement_list, name="announcement-list"),
    path("announcements/create/", announcement_create, name="announcement-create"),
    path(
        "announcements/<int:announcement_id>/edit/",
        announcement_update,
        name="announcement-update",
    ),
    path(
        "announcements/<int:announcement_id>/delete/",
        announcement_delete,
        name="announcement-delete",
    ),
    path("notifications/", notification_list, name="notification-list"),
    path(
        "notifications/<int:notification_id>/",
        notification_detail,
        name="notification-detail",
    ),
    path(
        "notifications/broadcast/",
        notification_broadcast,
        name="notification-broadcast",
    ),
    path(
        "notifications/reminders/",
        notification_reminder_center,
        name="notification-reminder-center",
    ),
    path(
        "notifications/preferences/",
        notification_preference_list,
        name="notification-preference-list",
    ),
    path(
        "notifications/preferences/<int:preference_id>/edit/",
        notification_preference_update,
        name="notification-preference-update",
    ),
    path(
        "notifications/templates/",
        notification_template_list,
        name="notification-template-list",
    ),
    path(
        "notifications/templates/<int:template_id>/edit/",
        notification_template_update,
        name="notification-template-update",
    ),
    path("notifications/devices/", push_device_list, name="push-device-list"),
    path(
        "notifications/devices/<int:device_id>/toggle-active/",
        push_device_toggle_active,
        name="push-device-toggle-active",
    ),
    path(
        "notifications/devices/<int:device_id>/send-test/",
        push_device_send_test,
        name="push-device-send-test",
    ),
    path("notifications/deliveries/", push_delivery_list, name="push-delivery-list"),
    path(
        "notifications/deliveries/<int:delivery_id>/",
        push_delivery_detail,
        name="push-delivery-detail",
    ),
    path(
        "notifications/deliveries/<int:delivery_id>/retry/",
        push_delivery_retry,
        name="push-delivery-retry",
    ),
    path(
        "notifications/push-diagnostics/",
        push_diagnostics,
        name="push-diagnostics",
    ),
    path(
        "notifications/push-diagnostics/deactivate-invalid/",
        push_deactivate_invalid_devices,
        name="push-deactivate-invalid-devices",
    ),
    path(
        "notifications/flutter-contract/",
        push_flutter_contract,
        name="push-flutter-contract",
    ),
    path(
        "notifications/<int:notification_id>/toggle-read/",
        notification_toggle_read,
        name="notification-toggle-read",
    ),
    path(
        "notifications/<int:notification_id>/delete/",
        notification_delete,
        name="notification-delete",
    ),
    path("classrooms/", classroom_list, name="classroom-list"),
    path("classrooms/create/", classroom_create, name="classroom-create"),
    path(
        "classrooms/<int:classroom_id>/edit/", classroom_update, name="classroom-update"
    ),
    path(
        "classrooms/<int:classroom_id>/delete/",
        classroom_delete,
        name="classroom-delete",
    ),
    path("sections/", section_list, name="section-list"),
    path("sections/create/", section_create, name="section-create"),
    path("sections/<int:section_id>/edit/", section_update, name="section-update"),
    path("sections/<int:section_id>/delete/", section_delete, name="section-delete"),
    path("subjects/", subject_list, name="subject-list"),
    path("subjects/create/", subject_create, name="subject-create"),
    path("subjects/<int:subject_id>/edit/", subject_update, name="subject-update"),
    path("subjects/<int:subject_id>/delete/", subject_delete, name="subject-delete"),
    path("academic-years/", academic_year_list, name="academic-year-list"),
    path("academic-years/create/", academic_year_create, name="academic-year-create"),
    path(
        "academic-years/<int:academic_year_id>/set-active/",
        academic_year_set_active,
        name="academic-year-set-active",
    ),
    path("promotion/", promotion_results, name="promotion-results"),
    path("promotion/calculate/", promotion_calculate, name="promotion-calculate"),
    path("promotion/publish/", promotion_publish, name="promotion-publish"),
    path(
        "promotion/results/<int:result_id>/",
        promotion_result_detail,
        name="promotion-result-detail",
    ),
    path(
        "teaching-assignments/",
        teaching_assignment_list,
        name="teaching-assignment-list",
    ),
    path(
        "teaching-assignments/create/",
        teaching_assignment_create,
        name="teaching-assignment-create",
    ),
    path(
        "teaching-assignments/<int:teaching_assignment_id>/edit/",
        teaching_assignment_update,
        name="teaching-assignment-update",
    ),
    path(
        "teaching-assignments/<int:teaching_assignment_id>/delete/",
        teaching_assignment_delete,
        name="teaching-assignment-delete",
    ),
]
