from django.urls import path
from .views import (
    admin_academic_years,
    admin_calculate_promotion_run,
    admin_promotion_result_detail,
    admin_promotion_results,
    teacher_assignments,
    teacher_students,
    teacher_create_attendance,
    teacher_create_grade,
    teacher_create_assignment,
    teacher_create_announcement,
    teacher_assignment_submissions,
    teacher_review_submission,
    teacher_upload_file,

    student_schedule,
    student_attendance,
    student_grades,
    student_assignments,
    student_assignment_submission,
    student_files,
    student_announcements,
    student_submit_assignment,
    student_submissions,
    student_year_result,

    parent_child_schedule,
    parent_child_attendance,
    parent_child_grades,
    parent_child_assignments,
    parent_child_files,
    parent_child_announcements,
    parent_child_submissions,
    parent_child_year_result,
)

urlpatterns = [
    path('admin/academic-years/', admin_academic_years, name='admin-academic-years'),
    path('admin/promotion-runs/calculate/', admin_calculate_promotion_run, name='admin-calculate-promotion-run'),
    path('admin/promotion-results/', admin_promotion_results, name='admin-promotion-results'),
    path('admin/promotion-results/<int:student_result_id>/', admin_promotion_result_detail, name='admin-promotion-result-detail'),

    path('teacher/assignments/', teacher_assignments, name='teacher-assignments'),
    path('teacher/students/', teacher_students, name='teacher-students'),

    path('teacher/attendance/create/', teacher_create_attendance, name='teacher-create-attendance'),
    path('teacher/grades/create/', teacher_create_grade, name='teacher-create-grade'),
    path('teacher/assignments/create/', teacher_create_assignment, name='teacher-create-assignment'),
    path('teacher/assignments/<int:assignment_id>/submissions/', teacher_assignment_submissions, name='teacher-assignment-submissions'),
    path('teacher/submissions/<int:submission_id>/review/', teacher_review_submission, name='teacher-review-submission'),
    path('teacher/announcements/create/', teacher_create_announcement, name='teacher-create-announcement'),
    path('teacher/files/upload/', teacher_upload_file, name='teacher-upload-file'),

    path('student/schedule/', student_schedule, name='student-schedule'),
    path('student/attendance/', student_attendance, name='student-attendance'),
    path('student/grades/', student_grades, name='student-grades'),
    path('student/assignments/', student_assignments, name='student-assignments'),
    path('student/assignments/<int:assignment_id>/submit/', student_submit_assignment, name='student-submit-assignment'),
    path('student/assignments/<int:assignment_id>/submission/', student_assignment_submission, name='student-assignment-submission'),
    path('student/submissions/', student_submissions, name='student-submissions'),
    path('student/files/', student_files, name='student-files'),
    path('student/announcements/', student_announcements, name='student-announcements'),
    path('student/year-result/', student_year_result, name='student-year-result'),

    path('parent/children/<int:student_id>/schedule/', parent_child_schedule, name='parent-child-schedule'),
    path('parent/children/<int:student_id>/attendance/', parent_child_attendance, name='parent-child-attendance'),
    path('parent/children/<int:student_id>/grades/', parent_child_grades, name='parent-child-grades'),
    path('parent/children/<int:student_id>/assignments/', parent_child_assignments, name='parent-child-assignments'),
    path('parent/children/<int:student_id>/submissions/', parent_child_submissions, name='parent-child-submissions'),
    path('parent/children/<int:student_id>/files/', parent_child_files, name='parent-child-files'),
    path('parent/children/<int:student_id>/announcements/', parent_child_announcements, name='parent-child-announcements'),
    path('parent/children/<int:student_id>/year-result/', parent_child_year_result, name='parent-child-year-result'),
]
