# Generated by Django 6.0.5 on 2026-06-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_announcement_assignment_grade_schedule_and_more'),
        ('accounts', '0002_parentprofile_studentprofile_parentlinkingcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment_submissions/')),
                ('text_answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('REVIEWED', 'Reviewed'), ('RESUBMITTED', 'Resubmitted')], default='SUBMITTED', max_length=20)),
                ('teacher_note', models.TextField(blank=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
