# Generated by Django 6.0.5 on 2026-06-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academicyear_promotionrun_studentyearresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyearresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentyearresult',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
