# Generated by Django 6.0.5 on 2026-06-28 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deep_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('general_enabled', models.BooleanField(default=True)),
                ('grade_enabled', models.BooleanField(default=True)),
                ('attendance_enabled', models.BooleanField(default=True)),
                ('assignment_enabled', models.BooleanField(default=True)),
                ('announcement_enabled', models.BooleanField(default=True)),
                ('invoice_enabled', models.BooleanField(default=True)),
                ('payment_enabled', models.BooleanField(default=True)),
                ('message_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('language', models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English')], default='AR', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SKIPPED', 'Skipped'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('INVALID_TOKEN', 'Invalid token')], default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.pushdevice')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_13d4c6_idx'), models.Index(fields=['notification', 'status'], name='notificatio_notific_df3801_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'device'), name='unique_push_delivery_per_device')],
            },
        ),
    ]
