# Generated by Django 6.0.5 on 2026-07-01 11:07

from django.db import migrations, models


DEFAULT_TEMPLATES = [
    (
        'assignment_created',
        'ASSIGNMENT',
        'AR',
        'واجب جديد',
        'تم نشر واجب جديد بعنوان "{assignment_title}" في مادة {subject_name}.',
    ),
    (
        'assignment_created',
        'ASSIGNMENT',
        'EN',
        'New assignment',
        'A new assignment "{assignment_title}" was posted for {subject_name}.',
    ),
    (
        'assignment_submitted',
        'ASSIGNMENT',
        'AR',
        'تم تسليم واجب',
        'قام {student_name} بتسليم واجب "{assignment_title}".',
    ),
    (
        'assignment_submitted',
        'ASSIGNMENT',
        'EN',
        'Assignment submitted',
        '{student_name} submitted "{assignment_title}".',
    ),
    (
        'assignment_reviewed',
        'ASSIGNMENT',
        'AR',
        'تمت مراجعة الواجب',
        'تمت مراجعة واجب "{assignment_title}". الحالة: {status}.',
    ),
    (
        'assignment_reviewed',
        'ASSIGNMENT',
        'EN',
        'Assignment reviewed',
        'Your assignment "{assignment_title}" has been reviewed. Status: {status}.',
    ),
    (
        'grade_created',
        'GRADE',
        'AR',
        'درجة جديدة',
        'تم تسجيل درجة {score}/{max_score} في {subject_name}.',
    ),
    (
        'grade_created',
        'GRADE',
        'EN',
        'New grade',
        'A grade of {score}/{max_score} was recorded for {subject_name}.',
    ),
    (
        'attendance_created',
        'ATTENDANCE',
        'AR',
        'تحديث حضور',
        'تم تسجيل حالة الحضور: {status} في {subject_name} بتاريخ {date}.',
    ),
    (
        'attendance_created',
        'ATTENDANCE',
        'EN',
        'Attendance update',
        'Attendance was marked as {status} for {subject_name} on {date}.',
    ),
    (
        'announcement_created',
        'ANNOUNCEMENT',
        'AR',
        '{announcement_title}',
        '{announcement_message}',
    ),
    (
        'announcement_created',
        'ANNOUNCEMENT',
        'EN',
        '{announcement_title}',
        '{announcement_message}',
    ),
    (
        'invoice_created',
        'INVOICE',
        'AR',
        'فاتورة جديدة',
        'تم إصدار فاتورة "{invoice_title}" بقيمة {amount} {currency}.',
    ),
    (
        'invoice_created',
        'INVOICE',
        'EN',
        'New invoice',
        'Invoice "{invoice_title}" was issued for {amount} {currency}.',
    ),
    (
        'payment_completed',
        'PAYMENT',
        'AR',
        'تم الدفع بنجاح',
        'تم دفع فاتورة "{invoice_title}" بنجاح. المبلغ: {amount} {currency}.',
    ),
    (
        'payment_completed',
        'PAYMENT',
        'EN',
        'Payment completed',
        'Invoice "{invoice_title}" was paid successfully. Amount: {amount} {currency}.',
    ),
    (
        'chat_message',
        'MESSAGE',
        'AR',
        'رسالة جديدة',
        'وصلتك رسالة جديدة من {sender_name}.',
    ),
    (
        'chat_message',
        'MESSAGE',
        'EN',
        'New message',
        'You received a new message from {sender_name}.',
    ),
    (
        'reminder_invoice_due',
        'INVOICE',
        'AR',
        'تذكير بفاتورة مستحقة',
        'الفاتورة "{invoice_title}" مستحقة بتاريخ {due_date}. المبلغ: {amount} {currency}.',
    ),
    (
        'reminder_invoice_due',
        'INVOICE',
        'EN',
        'Invoice due reminder',
        'Invoice "{invoice_title}" is due on {due_date}. Amount: {amount} {currency}.',
    ),
    (
        'reminder_assignment_due',
        'ASSIGNMENT',
        'AR',
        'تذكير بتسليم واجب',
        'موعد تسليم واجب "{assignment_title}" هو {due_date}.',
    ),
    (
        'reminder_assignment_due',
        'ASSIGNMENT',
        'EN',
        'Assignment due reminder',
        'Assignment "{assignment_title}" is due on {due_date}.',
    ),
    (
        'reminder_repeated_absence',
        'ATTENDANCE',
        'AR',
        'تنبيه غياب متكرر',
        'تم تسجيل {absence_count} حالات غياب للطالب {student_name}.',
    ),
    (
        'reminder_repeated_absence',
        'ATTENDANCE',
        'EN',
        'Repeated absence alert',
        '{student_name} has {absence_count} recorded absences.',
    ),
]


def seed_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')

    for key, notification_type, language, title_template, message_template in DEFAULT_TEMPLATES:
        NotificationTemplate.objects.update_or_create(
            key=key,
            language=language,
            defaults={
                'notification_type': notification_type,
                'title_template': title_template,
                'message_template': message_template,
                'is_active': True,
            },
        )


def remove_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    keys = {item[0] for item in DEFAULT_TEMPLATES}
    NotificationTemplate.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_deep_link_notificationpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('GRADE', 'Grade'), ('ATTENDANCE', 'Attendance'), ('ASSIGNMENT', 'Assignment'), ('ANNOUNCEMENT', 'Announcement'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment'), ('MESSAGE', 'Message')], default='GENERAL', max_length=20)),
                ('language', models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English')], default='AR', max_length=5)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', 'language'],
                'constraints': [models.UniqueConstraint(fields=('key', 'language'), name='unique_notification_template_language')],
            },
        ),
        migrations.RunPython(
            seed_notification_templates,
            remove_notification_templates,
        ),
    ]
